### PR TITLE
call restic backup script with nice (wip)

### PR DESCRIPTION
**Pull request by felixandersen**
Opening this PR as I did this change locally and thought it would add value to the role. Possibly not as is, with a default 10 priority, but an optional `priority` parameter? If given could prefix command with `/usr/bin/nice -n [priority]`. Let me know if this is interesting and I can refine the change.

### CODE REVIEW

**Comment by DO1JLR** [comment]
How did I not heard about nice before... :thinking: 

Sounds like a good idea. Please continue :heart:

**Comment by felixandersen** [comment]
@DO1JLR I have now added a conditional part in the service-template as well as some explanation in the README. Let me know if anything needs to be changed.

**Comment by kdebisschop** [comment]
The generic version of code is just to add

```
{% if item.service_options is defined %}
{% for key, value in item.service_options.items() %}
{{key}}={{value}}
{% endfor %}
{% endif %}
```

after `Type=oneshot` in restic.service.j2

Then in a job you can add e.g., 

```
    service_options:
      Nice: "-10"
      CPUQuota: "10%"
```

**Comment by felixandersen** [comment]
@kdebisschop that is great input and I agree it would be a better option. One potential drawback of a full dictionary approach would be complexity where a user might break a config by specifying something unexpected. I see it as a net positive tradeoff though.

I vote for full dictionary. At the very least we should use the Nice option in the service instead of wrapping the call like I did.

I have not heard anything from @DO1JLR in a while, but I am happy to rework my PR as @DO1JLR see fit.

**Comment by DO1JLR** [comment]
sorry

**Pull request merged**
